"""
Опциональные query-параметры для GET /training-composition-rules/.
"""
from typing import Optional
from uuid import UUID

from fastapi import Query


def training_composition_rule_filters(
    uuid: Optional[UUID] = Query(None, description="Фильтр по uuid правила"),
    actual: Optional[bool] = Query(None, description="Актуальная запись"),
    training_type: Optional[str] = Query(None, description="Тип тренировки (heavy_pull, light_recovery, …)"),
    program_goal: Optional[str] = Query(None, description="Цель программы (fat_loss, mass_gain, maintenance)"),
    program_week_index: Optional[int] = Query(None, description="Индекс недели программы (1–4)"),
    duration_target_minutes: Optional[int] = Query(None, description="Целевая длительность, мин"),
    location_scope: Optional[str] = Query(None, description="Область локации"),
    anchor_slots_count: Optional[int] = Query(None),
    main_slots_count: Optional[int] = Query(None),
    accessory_slots_count: Optional[int] = Query(None),
    core_slots_count: Optional[int] = Query(None),
    mobility_slots_count: Optional[int] = Query(None),
    allow_second_anchor: Optional[bool] = Query(None),
    anchor_sets: Optional[int] = Query(None),
    anchor_reps_min: Optional[int] = Query(None),
    anchor_reps_max: Optional[int] = Query(None),
    anchor_rest_seconds: Optional[int] = Query(None),
    main_sets: Optional[int] = Query(None),
    main_reps_min: Optional[int] = Query(None),
    main_reps_max: Optional[int] = Query(None),
    main_rest_seconds: Optional[int] = Query(None),
    accessory_sets: Optional[int] = Query(None),
    accessory_reps_min: Optional[int] = Query(None),
    accessory_reps_max: Optional[int] = Query(None),
    accessory_rest_seconds: Optional[int] = Query(None),
    core_sets: Optional[int] = Query(None),
    core_reps_min: Optional[int] = Query(None),
    core_reps_max: Optional[int] = Query(None),
    core_rest_seconds: Optional[int] = Query(None),
    mobility_sets: Optional[int] = Query(None),
    mobility_reps_min: Optional[int] = Query(None),
    mobility_reps_max: Optional[int] = Query(None),
    mobility_rest_seconds: Optional[int] = Query(None),
    notes_ru: Optional[str] = Query(None, description="Точное совпадение текста заметки"),
) -> dict:
    raw = {
        "uuid": uuid,
        "actual": actual,
        "training_type": training_type,
        "program_goal": program_goal,
        "program_week_index": program_week_index,
        "duration_target_minutes": duration_target_minutes,
        "location_scope": location_scope,
        "anchor_slots_count": anchor_slots_count,
        "main_slots_count": main_slots_count,
        "accessory_slots_count": accessory_slots_count,
        "core_slots_count": core_slots_count,
        "mobility_slots_count": mobility_slots_count,
        "allow_second_anchor": allow_second_anchor,
        "anchor_sets": anchor_sets,
        "anchor_reps_min": anchor_reps_min,
        "anchor_reps_max": anchor_reps_max,
        "anchor_rest_seconds": anchor_rest_seconds,
        "main_sets": main_sets,
        "main_reps_min": main_reps_min,
        "main_reps_max": main_reps_max,
        "main_rest_seconds": main_rest_seconds,
        "accessory_sets": accessory_sets,
        "accessory_reps_min": accessory_reps_min,
        "accessory_reps_max": accessory_reps_max,
        "accessory_rest_seconds": accessory_rest_seconds,
        "core_sets": core_sets,
        "core_reps_min": core_reps_min,
        "core_reps_max": core_reps_max,
        "core_rest_seconds": core_rest_seconds,
        "mobility_sets": mobility_sets,
        "mobility_reps_min": mobility_reps_min,
        "mobility_reps_max": mobility_reps_max,
        "mobility_rest_seconds": mobility_rest_seconds,
        "notes_ru": notes_ru,
    }
    return {k: v for k, v in raw.items() if v is not None}
