"""add_gif_id_to_exercise_reference

Revision ID: 04a0ab7309ca
Revises: 19c2fa3fd293
Create Date: 2025-09-09 22:02:02.726693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a0ab7309ca'
down_revision: Union[str, Sequence[str], None] = '19c2fa3fd293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_reference', sa.Column('gif_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_reference', 'files', ['gif_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_reference', type_='foreignkey')
    op.drop_column('exercise_reference', 'gif_id')
    # ### end Alembic commands ###
