"""add actual in training

Revision ID: 0d119072716a
Revises: 18a62e6d2d47
Create Date: 2025-07-24 00:32:28.407374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d119072716a'
down_revision: Union[str, Sequence[str], None] = '18a62e6d2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('actual', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'actual')
    # ### end Alembic commands ###
