"""stage and muscle_group in exercise_group may be null

Revision ID: 18a62e6d2d47
Revises: 3e33f2607c7a
Create Date: 2025-07-24 00:16:22.851839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a62e6d2d47'
down_revision: Union[str, Sequence[str], None] = '3e33f2607c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_group', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise_group', 'stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise_group', 'stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_group', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
