"""empty message

Revision ID: 19c2fa3fd293
Revises: make_cat_id_nullable
Create Date: 2025-09-09 21:09:06.766223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c2fa3fd293'
down_revision: Union[str, Sequence[str], None] = 'make_cat_id_nullable'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('achievement_types_uuid_key'), 'achievement_types', type_='unique')
    op.create_index(op.f('ix_achievement_types_uuid'), 'achievement_types', ['uuid'], unique=True)
    op.drop_constraint(op.f('achievements_uuid_key'), 'achievements', type_='unique')
    op.create_index(op.f('ix_achievements_uuid'), 'achievements', ['uuid'], unique=True)
    op.add_column('exercise_reference', sa.Column('technique_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_reference', 'technique_description')
    op.drop_index(op.f('ix_achievements_uuid'), table_name='achievements')
    op.create_unique_constraint(op.f('achievements_uuid_key'), 'achievements', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_achievement_types_uuid'), table_name='achievement_types')
    op.create_unique_constraint(op.f('achievement_types_uuid_key'), 'achievement_types', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
