"""add week and weekdat to user_training table

Revision ID: 1bf1ab3ec3cd
Revises: 52423161059e
Create Date: 2025-07-14 19:02:26.033727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf1ab3ec3cd'
down_revision: Union[str, Sequence[str], None] = '52423161059e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_training', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('user_training', sa.Column('weekday', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_training', 'weekday')
    op.drop_column('user_training', 'week')
    # ### end Alembic commands ###
