"""add user_id to last_values

Revision ID: 219c7ad26059
Revises: 64b2ab7ac0a6
Create Date: 2025-12-24 19:08:36.337284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219c7ad26059'
down_revision: Union[str, Sequence[str], None] = '64b2ab7ac0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('last_values', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('last_values_code_key'), 'last_values', type_='unique')
    op.create_foreign_key(None, 'last_values', 'user', ['user_id'], ['id'])
    # Создаем составное уникальное ограничение на (user_id, code)
    op.create_unique_constraint('uq_last_values_user_code', 'last_values', ['user_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем один DO блок для безопасного удаления всех ограничений
    # Это предотвращает прерывание транзакции при отсутствии ограничений
    op.execute(sa.text("""
        DO $$ 
        DECLARE 
            fk_name text;
        BEGIN
            -- Безопасное удаление составного уникального ограничения
            BEGIN
                ALTER TABLE last_values DROP CONSTRAINT IF EXISTS uq_last_values_user_code;
            EXCEPTION WHEN OTHERS THEN
                NULL; -- Игнорируем любые ошибки
            END;
            
            -- Безопасное удаление foreign key
            BEGIN
                SELECT conname INTO fk_name 
                FROM pg_constraint 
                WHERE contype = 'f' 
                AND conrelid = 'last_values'::regclass
                AND confrelid = 'user'::regclass
                LIMIT 1;
                
                IF fk_name IS NOT NULL THEN
                    EXECUTE format('ALTER TABLE last_values DROP CONSTRAINT IF EXISTS %I', fk_name);
                END IF;
            EXCEPTION WHEN OTHERS THEN
                NULL; -- Игнорируем любые ошибки
            END;
        END $$;
    """))
    
    op.create_unique_constraint(op.f('last_values_code_key'), 'last_values', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_column('last_values', 'user_id')
    # ### end Alembic commands ###
