"""auto migration

Revision ID: 3f32087843a6
Revises: e213876a5e35
Create Date: 2025-08-05 23:25:45.159201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f32087843a6'
down_revision: Union[str, Sequence[str], None] = 'e213876a5e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем поле только если его еще нет
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('exercise_reference')]
    if 'video_id' not in columns:
        op.add_column('exercise_reference', sa.Column('video_id', sa.Integer(), nullable=True))
        # Добавляем внешний ключ только если его еще нет
        fk_names = [fk['name'] for fk in inspector.get_foreign_keys('exercise_reference') if fk['constrained_columns'] == ['video_id']]
        if not fk_names:
            op.create_foreign_key(None, 'exercise_reference', 'files', ['video_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_reference', type_='foreignkey')
    op.drop_column('exercise_reference', 'video_id')
    # ### end Alembic commands ###
