"""auto migration

Revision ID: 3f32087843a6
Revises: e213876a5e35
Create Date: 2025-08-05 23:25:45.159201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f32087843a6'
down_revision: Union[str, Sequence[str], None] = 'e213876a5e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_reference', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_reference', 'files', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_reference', type_='foreignkey')
    op.drop_column('exercise_reference', 'video_id')
    # ### end Alembic commands ###
