"""add exercise reference

Revision ID: 40768d1aa026
Revises: 6e072cdbe915
Create Date: 2025-07-23 22:43:17.974693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40768d1aa026'
down_revision: Union[str, Sequence[str], None] = '6e072cdbe915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('muscle_group', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_reference_uuid'), 'exercise_reference', ['uuid'], unique=True)
    op.add_column('training', sa.Column('exercise_reference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'training', 'exercise_reference', ['exercise_reference_id'], ['id'])
    op.drop_index(op.f('ix_user_training_program_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_stage'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_status'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_training_date'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_training_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_user_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_user_program_date'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_user_program_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_user_program_status'), table_name='user_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_training_user_program_status'), 'user_training', ['user_program_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_training_user_program_id'), 'user_training', ['user_program_id'], unique=False)
    op.create_index(op.f('ix_user_training_user_program_date'), 'user_training', ['user_program_id', 'training_date'], unique=False)
    op.create_index(op.f('ix_user_training_user_id'), 'user_training', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_training_training_id'), 'user_training', ['training_id'], unique=False)
    op.create_index(op.f('ix_user_training_training_date'), 'user_training', ['training_date'], unique=False)
    op.create_index(op.f('ix_user_training_status'), 'user_training', ['status'], unique=False)
    op.create_index(op.f('ix_user_training_stage'), 'user_training', ['stage'], unique=False)
    op.create_index(op.f('ix_user_training_program_id'), 'user_training', ['program_id'], unique=False)
    op.drop_constraint(None, 'training', type_='foreignkey')
    op.drop_column('training', 'exercise_reference_id')
    op.drop_index(op.f('ix_exercise_reference_uuid'), table_name='exercise_reference')
    op.drop_table('exercise_reference')
    # ### end Alembic commands ###
