"""add actual flag to user

Revision ID: 4cf0dd82ea1e
Revises: fe027d9412c1
Create Date: 2025-11-11 20:57:34.361839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf0dd82ea1e'
down_revision: Union[str, Sequence[str], None] = 'fe027d9412c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'actual')
    # ### end Alembic commands ###
