"""add user_favorite_exercises table

Revision ID: 58c47d8a16f0
Revises: 219c7ad26059
Create Date: 2025-12-24 21:40:40.826948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c47d8a16f0'
down_revision: Union[str, Sequence[str], None] = '219c7ad26059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_reference_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_reference_id'], ['exercise_reference.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_reference_id', name='uq_user_favorite_exercise')
    )
    op.create_index(op.f('ix_user_favorite_exercises_uuid'), 'user_favorite_exercises', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_exercises_uuid'), table_name='user_favorite_exercises')
    op.drop_table('user_favorite_exercises')
    # ### end Alembic commands ###
