"""add is_rest_day  to user_training table

Revision ID: 6509afd55598
Revises: 1bf1ab3ec3cd
Create Date: 2025-07-14 19:35:28.921315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6509afd55598'
down_revision: Union[str, Sequence[str], None] = '1bf1ab3ec3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_training', sa.Column('is_rest_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_training', 'is_rest_day')
    # ### end Alembic commands ###
