"""add_files_table

Revision ID: 6c6c98f376b3
Revises: make_user_fields_optional
Create Date: 2025-07-13 11:01:29.083512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6c98f376b3'
down_revision: Union[str, Sequence[str], None] = 'make_user_fields_optional'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_training', 'stage',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_training', 'stage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
