"""add exercise_reference_id to exercise table

Revision ID: 796763dd038d
Revises: 40768d1aa026
Create Date: 2025-07-23 22:55:40.085725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796763dd038d'
down_revision: Union[str, Sequence[str], None] = '40768d1aa026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('exercise_reference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise', 'exercise_reference', ['exercise_reference_id'], ['id'])
    op.add_column('exercise_reference', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_reference', 'files', ['image_id'], ['id'])
    op.drop_constraint(op.f('training_exercise_reference_id_fkey'), 'training', type_='foreignkey')
    op.drop_column('training', 'exercise_reference_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('exercise_reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('training_exercise_reference_id_fkey'), 'training', 'exercise_reference', ['exercise_reference_id'], ['id'])
    op.drop_constraint(None, 'exercise_reference', type_='foreignkey')
    op.drop_column('exercise_reference', 'image_id')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_column('exercise', 'exercise_reference_id')
    # ### end Alembic commands ###
