"""add exercise_type and user_id to exercise_reference table

Revision ID: 84dc237d2722
Revises: 796763dd038d
Create Date: 2025-07-23 23:08:24.576879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dc237d2722'
down_revision: Union[str, Sequence[str], None] = '796763dd038d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_reference', sa.Column('exercise_type', sa.String(), nullable=True))
    op.add_column('exercise_reference', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'exercise_reference', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise_reference', type_='foreignkey')
    op.drop_column('exercise_reference', 'user_id')
    op.drop_column('exercise_reference', 'exercise_type')
    # ### end Alembic commands ###
