"""Add equipment_name and auxiliary_muscle_groups to exercise_reference

Revision ID: 883ceefacb58
Revises: bb26141c2444
Create Date: 2025-10-18 23:12:18.029349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883ceefacb58'
down_revision: Union[str, Sequence[str], None] = 'bb26141c2444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_reference', sa.Column('equipment_name', sa.String(), nullable=True))
    op.add_column('exercise_reference', sa.Column('auxiliary_muscle_groups', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_reference', 'auxiliary_muscle_groups')
    op.drop_column('exercise_reference', 'equipment_name')
    # ### end Alembic commands ###
