"""update_meal_plans_table_structure

Revision ID: 888f283b245f
Revises: c7d8e9f0a1b2
Create Date: 2026-01-09 21:16:25.023858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888f283b245f'
down_revision: Union[str, Sequence[str], None] = 'c7d8e9f0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем constraint'ы с проверкой существования
    op.execute("ALTER TABLE calorie_calculations DROP CONSTRAINT IF EXISTS calorie_calculations_uuid_key")
    op.drop_index(op.f('ix_calorie_calculations_uuid'), table_name='calorie_calculations')
    op.create_index(op.f('ix_calorie_calculations_uuid'), 'calorie_calculations', ['uuid'], unique=True)
    op.execute("ALTER TABLE daily_targets DROP CONSTRAINT IF EXISTS daily_targets_uuid_key")
    op.drop_index(op.f('ix_daily_targets_uuid'), table_name='daily_targets')
    op.create_index(op.f('ix_daily_targets_uuid'), 'daily_targets', ['uuid'], unique=True)
    op.execute("ALTER TABLE food_recognition DROP CONSTRAINT IF EXISTS food_recognition_uuid_key")
    op.drop_index(op.f('ix_food_recognition_uuid'), table_name='food_recognition')
    op.create_index(op.f('ix_food_recognition_uuid'), 'food_recognition', ['uuid'], unique=True)
    op.execute("ALTER TABLE last_values DROP CONSTRAINT IF EXISTS last_values_user_id_code_key")
    op.execute("ALTER TABLE last_values DROP CONSTRAINT IF EXISTS last_values_uuid_key")
    op.drop_index(op.f('ix_last_values_uuid'), table_name='last_values')
    op.create_index(op.f('ix_last_values_uuid'), 'last_values', ['uuid'], unique=True)
    op.create_unique_constraint('uq_last_values_user_code', 'last_values', ['user_id', 'code'])
    op.add_column('meal_plans', sa.Column('use_all_recipes', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('meal_plans', sa.Column('target_nutrition', sa.Text(), nullable=True))
    op.add_column('meal_plans', sa.Column('response_data', sa.Text(), nullable=True))
    op.execute("ALTER TABLE meal_plans DROP CONSTRAINT IF EXISTS meal_plans_uuid_key")
    op.drop_index(op.f('ix_meal_plans_uuid'), table_name='meal_plans')
    op.create_index(op.f('ix_meal_plans_uuid'), 'meal_plans', ['uuid'], unique=True)
    op.drop_column('meal_plans', 'target_calories')
    op.drop_column('meal_plans', 'target_proteins')
    op.drop_column('meal_plans', 'target_fats')
    op.drop_column('meal_plans', 'max_repeats_per_week')
    op.drop_column('meal_plans', 'plan_data')
    op.drop_column('meal_plans', 'target_carbs')
    op.drop_column('meal_plans', 'include_soup_in_lunch')
    op.drop_column('meal_plans', 'recommendations')
    op.execute("ALTER TABLE meals DROP CONSTRAINT IF EXISTS meals_uuid_key")
    op.drop_index(op.f('ix_meals_uuid'), table_name='meals')
    op.create_index(op.f('ix_meals_uuid'), 'meals', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meals_uuid'), table_name='meals')
    op.create_index(op.f('ix_meals_uuid'), 'meals', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('meals_uuid_key'), 'meals', ['uuid'], postgresql_nulls_not_distinct=False)
    op.add_column('meal_plans', sa.Column('recommendations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('include_soup_in_lunch', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('target_carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('plan_data', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('max_repeats_per_week', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('meal_plans', sa.Column('target_fats', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('target_proteins', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('meal_plans', sa.Column('target_calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_meal_plans_uuid'), table_name='meal_plans')
    op.create_index(op.f('ix_meal_plans_uuid'), 'meal_plans', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('meal_plans_uuid_key'), 'meal_plans', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('meal_plans', 'response_data')
    op.drop_column('meal_plans', 'target_nutrition')
    op.drop_column('meal_plans', 'use_all_recipes')
    op.drop_constraint('uq_last_values_user_code', 'last_values', type_='unique')
    op.drop_index(op.f('ix_last_values_uuid'), table_name='last_values')
    op.create_index(op.f('ix_last_values_uuid'), 'last_values', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('last_values_uuid_key'), 'last_values', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('last_values_user_id_code_key'), 'last_values', ['user_id', 'code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_food_recognition_uuid'), table_name='food_recognition')
    op.create_index(op.f('ix_food_recognition_uuid'), 'food_recognition', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('food_recognition_uuid_key'), 'food_recognition', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_daily_targets_uuid'), table_name='daily_targets')
    op.create_index(op.f('ix_daily_targets_uuid'), 'daily_targets', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('daily_targets_uuid_key'), 'daily_targets', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_calorie_calculations_uuid'), table_name='calorie_calculations')
    op.create_index(op.f('ix_calorie_calculations_uuid'), 'calorie_calculations', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('calorie_calculations_uuid_key'), 'calorie_calculations', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
