"""some fix

Revision ID: 8eaa14d20cc0
Revises: e2904f2259eb
Create Date: 2025-07-14 21:07:09.947607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaa14d20cc0'
down_revision: Union[str, Sequence[str], None] = 'e2904f2259eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('sets_count', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('reps_count', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('rest_time', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('with_weight', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'with_weight')
    op.drop_column('exercise', 'rest_time')
    op.drop_column('exercise', 'reps_count')
    op.drop_column('exercise', 'sets_count')
    # ### end Alembic commands ###
