"""add email verification functionality

Revision ID: a140399bc302
Revises: 29a5d1434771
Create Date: 2025-07-29 23:42:09.147118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a140399bc302'
down_revision: Union[str, Sequence[str], None] = '29a5d1434771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
