"""Add promo codes table and promo_code_id to payments

Revision ID: b1b0c56515aa
Revises: add_program_indexes_opt
Create Date: 2026-01-17 15:54:04.843928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b0c56515aa'
down_revision: Union[str, Sequence[str], None] = 'add_program_indexes_opt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_promo_codes_uuid'), 'promo_codes', ['uuid'], unique=True)
    op.add_column('payments', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_payments_promo_code_id', 'payments', 'promo_codes', ['promo_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_payments_promo_code_id', 'payments', type_='foreignkey')
    op.drop_column('payments', 'promo_code_id')
    op.drop_index(op.f('ix_promo_codes_uuid'), table_name='promo_codes')
    op.drop_table('promo_codes')
    # ### end Alembic commands ###
