"""add email_notifications_enabled to user table

Revision ID: bed84e8e1044
Revises: 49a0057de158
Create Date: 2026-01-28 23:18:03.847891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed84e8e1044'
down_revision: Union[str, Sequence[str], None] = '49a0057de158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_image_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_reference_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_type'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_user_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_video_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_video_preview_id'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_reference_exercise_type'), table_name='exercise_reference')
    op.drop_index(op.f('ix_exercise_reference_gif_id'), table_name='exercise_reference')
    op.drop_index(op.f('ix_exercise_reference_image_id'), table_name='exercise_reference')
    op.drop_index(op.f('ix_exercise_reference_user_id'), table_name='exercise_reference')
    op.drop_index(op.f('ix_exercise_reference_video_id'), table_name='exercise_reference')
    op.drop_index(op.f('ix_program_category_id'), table_name='program')
    op.drop_index(op.f('ix_program_image_id'), table_name='program')
    op.drop_index(op.f('ix_program_type_actual'), table_name='program')
    op.drop_index(op.f('ix_program_user_id'), table_name='program')
    op.alter_column('training', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_training_image_id'), table_name='training')
    op.drop_index(op.f('ix_training_program_id'), table_name='training')
    op.drop_index(op.f('ix_training_type_actual'), table_name='training')
    op.drop_index(op.f('ix_training_user_id'), table_name='training')
    op.add_column('user', sa.Column('email_notifications_enabled', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_user_exercise_exercise_id'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_exercise_program_id'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_exercise_status'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_exercise_training_date'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_exercise_training_id'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_exercise_user_id'), table_name='user_exercise')
    op.drop_index(op.f('ix_user_training_program_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_status'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_training_date'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_training_id'), table_name='user_training')
    op.drop_index(op.f('ix_user_training_user_id'), table_name='user_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_training_user_id'), 'user_training', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_training_training_id'), 'user_training', ['training_id'], unique=False)
    op.create_index(op.f('ix_user_training_training_date'), 'user_training', ['training_date'], unique=False)
    op.create_index(op.f('ix_user_training_status'), 'user_training', ['status'], unique=False)
    op.create_index(op.f('ix_user_training_program_id'), 'user_training', ['program_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_user_id'), 'user_exercise', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_training_id'), 'user_exercise', ['training_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_training_date'), 'user_exercise', ['training_date'], unique=False)
    op.create_index(op.f('ix_user_exercise_status'), 'user_exercise', ['status'], unique=False)
    op.create_index(op.f('ix_user_exercise_program_id'), 'user_exercise', ['program_id'], unique=False)
    op.create_index(op.f('ix_user_exercise_exercise_id'), 'user_exercise', ['exercise_id'], unique=False)
    op.drop_column('user', 'email_notifications_enabled')
    op.create_index(op.f('ix_training_user_id'), 'training', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_type_actual'), 'training', ['training_type', 'actual'], unique=False)
    op.create_index(op.f('ix_training_program_id'), 'training', ['program_id'], unique=False)
    op.create_index(op.f('ix_training_image_id'), 'training', ['image_id'], unique=False)
    op.alter_column('training', 'muscle_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_program_user_id'), 'program', ['user_id'], unique=False)
    op.create_index(op.f('ix_program_type_actual'), 'program', ['program_type', 'actual'], unique=False)
    op.create_index(op.f('ix_program_image_id'), 'program', ['image_id'], unique=False)
    op.create_index(op.f('ix_program_category_id'), 'program', ['category_id'], unique=False)
    op.create_index(op.f('ix_exercise_reference_video_id'), 'exercise_reference', ['video_id'], unique=False)
    op.create_index(op.f('ix_exercise_reference_user_id'), 'exercise_reference', ['user_id'], unique=False)
    op.create_index(op.f('ix_exercise_reference_image_id'), 'exercise_reference', ['image_id'], unique=False)
    op.create_index(op.f('ix_exercise_reference_gif_id'), 'exercise_reference', ['gif_id'], unique=False)
    op.create_index(op.f('ix_exercise_reference_exercise_type'), 'exercise_reference', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercise_video_preview_id'), 'exercise', ['video_preview_id'], unique=False)
    op.create_index(op.f('ix_exercise_video_id'), 'exercise', ['video_id'], unique=False)
    op.create_index(op.f('ix_exercise_user_id'), 'exercise', ['user_id'], unique=False)
    op.create_index(op.f('ix_exercise_type'), 'exercise', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_exercise_reference_id'), 'exercise', ['exercise_reference_id'], unique=False)
    op.create_index(op.f('ix_exercise_image_id'), 'exercise', ['image_id'], unique=False)
    # ### end Alembic commands ###
