"""add_stage_to_user_training

Revision ID: bedcc009ce6e
Revises: b2c3d4e5f6a7
Create Date: 2025-07-12 00:39:47.741186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bedcc009ce6e'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('program', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('program', 'schedule_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'weekly'::character varying"))
    op.alter_column('user_program', 'schedule_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Добавляем поле stage как nullable сначала
    op.add_column('user_training', sa.Column('stage', sa.Integer(), nullable=True))
    
    # Заполняем существующие записи значением по умолчанию
    op.execute("UPDATE user_training SET stage = 1 WHERE stage IS NULL")
    
    # Делаем поле NOT NULL
    op.alter_column('user_training', 'stage', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем поле stage
    op.drop_column('user_training', 'stage')
    op.alter_column('user_program', 'schedule_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('program', 'schedule_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'weekly'::character varying"))
    op.alter_column('program', 'difficulty_level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
