"""add_avatar_id_to_user

Revision ID: dde85285caa4
Revises: create_files_table_manual
Create Date: 2025-07-13 11:38:12.585321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde85285caa4'
down_revision: Union[str, Sequence[str], None] = 'create_files_table_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_uuid_key'), 'files', type_='unique')
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=True)
    op.add_column('user', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'files', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'avatar_id')
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=False)
    op.create_unique_constraint(op.f('files_uuid_key'), 'files', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
