"""bug fix

Revision ID: e2904f2259eb
Revises: 6509afd55598
Create Date: 2025-07-14 19:38:24.862178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2904f2259eb'
down_revision: Union[str, Sequence[str], None] = '6509afd55598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_training', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_training', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
