"""add food functionality tables (food_recognition, recipes, calorie_calculator, food_progress, meal_plans)

Revision ID: f10fef625749
Revises: a0b28d3ceffa
Create Date: 2026-01-04 18:01:35.653810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10fef625749'
down_revision: Union[str, Sequence[str], None] = 'a0b28d3ceffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum типы с проверкой существования через SQL DO блок
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE goalenum AS ENUM ('weight_loss', 'muscle_gain', 'maintenance');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE genderenum AS ENUM ('male', 'female');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Создаем таблицу calorie_calculations через SQL, чтобы избежать повторного создания enum типов
    op.execute("""
        CREATE TABLE IF NOT EXISTS calorie_calculations (
            id SERIAL PRIMARY KEY,
            uuid UUID NOT NULL UNIQUE,
            actual BOOLEAN NOT NULL DEFAULT true,
            user_id INTEGER NOT NULL REFERENCES "user"(id),
            goal goalenum NOT NULL,
            gender genderenum NOT NULL,
            weight DOUBLE PRECISION NOT NULL,
            height DOUBLE PRECISION NOT NULL,
            age INTEGER NOT NULL,
            activity_coefficient VARCHAR NOT NULL,
            bmr DOUBLE PRECISION NOT NULL,
            tdee DOUBLE PRECISION NOT NULL,
            calories_for_weight_loss TEXT,
            calories_for_gain TEXT,
            calories_for_maintenance TEXT,
            created_at TIMESTAMP NOT NULL,
            updated_at TIMESTAMP NOT NULL
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_calorie_calculations_uuid ON calorie_calculations (uuid)")
    op.create_table('daily_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=False),
    sa.Column('target_proteins', sa.Float(), nullable=False),
    sa.Column('target_fats', sa.Float(), nullable=False),
    sa.Column('target_carbs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_targets_uuid'), 'daily_targets', ['uuid'], unique=True)
    op.create_table('food_recognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('json_response', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('proteins_per_100g', sa.Float(), nullable=True),
    sa.Column('fats_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('volume_ml', sa.Float(), nullable=True),
    sa.Column('estimated_portion_size', sa.String(), nullable=True),
    sa.Column('calories_total', sa.Float(), nullable=True),
    sa.Column('proteins_total', sa.Float(), nullable=True),
    sa.Column('fats_total', sa.Float(), nullable=True),
    sa.Column('carbs_total', sa.Float(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('recommendations_tip', sa.Text(), nullable=True),
    sa.Column('recommendations_alternative', sa.Text(), nullable=True),
    sa.Column('micronutrients', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_recognition_uuid'), 'food_recognition', ['uuid'], unique=True)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('max_repeats_per_week', sa.Integer(), nullable=True),
    sa.Column('allowed_recipe_uuids', sa.Text(), nullable=True),
    sa.Column('include_soup_in_lunch', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=False),
    sa.Column('target_proteins', sa.Float(), nullable=False),
    sa.Column('target_fats', sa.Float(), nullable=False),
    sa.Column('target_carbs', sa.Float(), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_uuid'), 'meal_plans', ['uuid'], unique=True)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_datetime', sa.DateTime(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('proteins', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('target_calories', sa.Float(), nullable=False),
    sa.Column('target_proteins', sa.Float(), nullable=False),
    sa.Column('target_fats', sa.Float(), nullable=False),
    sa.Column('target_carbs', sa.Float(), nullable=False),
    sa.Column('remaining_calories', sa.Float(), nullable=False),
    sa.Column('remaining_proteins', sa.Float(), nullable=False),
    sa.Column('remaining_fats', sa.Float(), nullable=False),
    sa.Column('remaining_carbs', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_uuid'), 'meals', ['uuid'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('actual', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('recipe', sa.Text(), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('proteins_per_100g', sa.Float(), nullable=True),
    sa.Column('fats_per_100g', sa.Float(), nullable=True),
    sa.Column('carbs_per_100g', sa.Float(), nullable=True),
    sa.Column('calories_per_portion', sa.Float(), nullable=True),
    sa.Column('proteins_per_portion', sa.Float(), nullable=True),
    sa.Column('fats_per_portion', sa.Float(), nullable=True),
    sa.Column('carbs_per_portion', sa.Float(), nullable=True),
    sa.Column('portions_count', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('cooking_time', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_uuid'), 'recipes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_uuid'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meals_uuid'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_meal_plans_uuid'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_food_recognition_uuid'), table_name='food_recognition')
    op.drop_table('food_recognition')
    op.drop_index(op.f('ix_daily_targets_uuid'), table_name='daily_targets')
    op.drop_table('daily_targets')
    op.drop_index(op.f('ix_calorie_calculations_uuid'), table_name='calorie_calculations')
    op.drop_table('calorie_calculations')
    # ### end Alembic commands ###
