"""add weight to the exrcise table

Revision ID: f961f7c58c7c
Revises: 6095bd8218d7
Create Date: 2025-07-19 18:36:24.399908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f961f7c58c7c'
down_revision: Union[str, Sequence[str], None] = '6095bd8218d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'weight')
    # ### end Alembic commands ###
