"""add original_name to exercise_reference

Revision ID: fe027d9412c1
Revises: 883ceefacb58
Create Date: 2025-10-29 22:47:20.172688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe027d9412c1'
down_revision: Union[str, Sequence[str], None] = '883ceefacb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_reference', sa.Column('original_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_reference', 'original_name')
    # ### end Alembic commands ###
